-- Run once in the Supabase SQL Editor.
-- The browser receives access only to the two RPC functions below.

create table if not exists public.stimuli (
  id bigint generated by default as identity primary key,
  file_name text not null unique,
  public_path text not null unique,
  target_labels smallint not null default 10 check (target_labels > 0),
  completed_labels smallint not null default 0 check (completed_labels >= 0),
  reserved_labels smallint not null default 0 check (reserved_labels >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  participant_id text not null,
  prolific_study_id text not null,
  prolific_session_id text not null unique,
  attribute_order text not null check (
    attribute_order in (
      'glossiness_then_metallicness',
      'metallicness_then_glossiness'
    )
  ),
  status text not null default 'assigned' check (
    status in ('assigned', 'completed', 'expired')
  ),
  assigned_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (participant_id, prolific_study_id)
);

create table if not exists public.session_assignments (
  study_session_id uuid not null references public.study_sessions(id) on delete cascade,
  stimulus_id bigint not null references public.stimuli(id),
  trial_number smallint not null check (trial_number between 1 and 80),
  completed boolean not null default false,
  primary key (study_session_id, stimulus_id),
  unique (study_session_id, trial_number)
);

create table if not exists public.ratings (
  study_session_id uuid not null references public.study_sessions(id) on delete cascade,
  stimulus_id bigint not null references public.stimuli(id),
  glossiness smallint not null check (glossiness between 1 and 7),
  metallicness smallint not null check (metallicness between 1 and 7),
  response_time_ms integer not null check (response_time_ms >= 0),
  created_at timestamptz not null default now(),
  primary key (study_session_id, stimulus_id)
);

create table if not exists public.initial_ratings (
  study_session_id uuid not null references public.study_sessions(id) on delete cascade,
  stimulus text not null,
  trial_number smallint not null check (trial_number between 1 and 4),
  glossiness smallint not null check (glossiness between 1 and 7),
  metallicness smallint not null check (metallicness between 1 and 7),
  response_time_ms integer not null check (response_time_ms >= 0),
  created_at timestamptz not null default now(),
  primary key (study_session_id, trial_number),
  unique (study_session_id, stimulus)
);

create index if not exists stimuli_coverage_idx
  on public.stimuli (active, completed_labels, reserved_labels, target_labels);
create index if not exists assignments_stimulus_idx
  on public.session_assignments (stimulus_id);

alter table public.stimuli enable row level security;
alter table public.study_sessions enable row level security;
alter table public.session_assignments enable row level security;
alter table public.ratings enable row level security;
alter table public.initial_ratings enable row level security;

revoke all on public.stimuli from anon, authenticated;
revoke all on public.study_sessions from anon, authenticated;
revoke all on public.session_assignments from anon, authenticated;
revoke all on public.ratings from anon, authenticated;
revoke all on public.initial_ratings from anon, authenticated;

create or replace function public.claim_study_assignment(
  p_participant_id text,
  p_study_id text,
  p_prolific_session_id text,
  p_attribute_order text
)
returns table (
  study_session_id uuid,
  stimulus_id bigint,
  file_name text,
  public_path text,
  trial_number integer
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_study_session_id uuid;
  v_stimulus_ids bigint[];
begin
  if coalesce(length(trim(p_participant_id)), 0) = 0
     or coalesce(length(trim(p_study_id)), 0) = 0
     or coalesce(length(trim(p_prolific_session_id)), 0) = 0 then
    raise exception 'Missing Prolific identifiers';
  end if;

  if p_attribute_order not in (
    'glossiness_then_metallicness',
    'metallicness_then_glossiness'
  ) then
    raise exception 'Invalid attribute order';
  end if;

  -- Release assignments from clearly abandoned sessions so that their
  -- stimuli can still reach the requested number of completed labels.
  with stale_sessions as materialized (
    select s.id
    from public.study_sessions as s
    where s.status = 'assigned'
      and s.assigned_at < now() - interval '6 hours'
    for update skip locked
  ), released_reservations as (
    update public.stimuli as s
    set reserved_labels = greatest(
      0,
      s.reserved_labels - expired.reservation_count
    )::smallint
    from (
      select a.stimulus_id, count(*)::integer as reservation_count
      from public.session_assignments as a
      join stale_sessions as stale on stale.id = a.study_session_id
      group by a.stimulus_id
    ) as expired
    where s.id = expired.stimulus_id
  )
  update public.study_sessions as s
  set status = 'expired'
  where s.id in (select stale.id from stale_sessions as stale);

  select s.id
    into v_study_session_id
  from public.study_sessions as s
  where (
    s.prolific_session_id = p_prolific_session_id
    or (s.participant_id = p_participant_id and s.prolific_study_id = p_study_id)
  )
    and s.status <> 'expired'
  order by s.assigned_at desc
  limit 1;

  if v_study_session_id is null then
    insert into public.study_sessions (
      participant_id,
      prolific_study_id,
      prolific_session_id,
      attribute_order
    ) values (
      p_participant_id,
      p_study_id,
      p_prolific_session_id,
      p_attribute_order
    )
    returning id into v_study_session_id;

    select array_agg(candidate.id order by candidate.coverage, candidate.tie_break)
      into v_stimulus_ids
    from (
      select
        s.id,
        s.completed_labels + s.reserved_labels as coverage,
        random() as tie_break
      from public.stimuli as s
      where s.active
        and s.completed_labels + s.reserved_labels < s.target_labels
      order by coverage, tie_break
      for update skip locked
      limit 80
    ) as candidate;

    if coalesce(array_length(v_stimulus_ids, 1), 0) <> 80 then
      raise exception 'Not enough available stimuli for a complete session';
    end if;

    insert into public.session_assignments (
      study_session_id,
      stimulus_id,
      trial_number
    )
    select v_study_session_id, item.stimulus_id, item.ordinality::smallint
    from unnest(v_stimulus_ids) with ordinality as item(stimulus_id, ordinality);

    update public.stimuli as s
    set reserved_labels = s.reserved_labels + 1
    where s.id = any(v_stimulus_ids);
  end if;

  return query
  select
    a.study_session_id,
    s.id,
    s.file_name,
    s.public_path,
    a.trial_number::integer
  from public.session_assignments as a
  join public.stimuli as s on s.id = a.stimulus_id
  where a.study_session_id = v_study_session_id
  order by a.trial_number;
end;
$$;

create or replace function public.submit_study_session(
  p_study_session_id uuid,
  p_participant_id text,
  p_initial_responses jsonb,
  p_responses jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_status text;
  v_inserted integer;
  v_initial_inserted integer;
begin
  select s.status
    into v_status
  from public.study_sessions as s
  where s.id = p_study_session_id
    and s.participant_id = p_participant_id
  for update;

  if v_status is null then
    raise exception 'Invalid study session';
  end if;
  if v_status = 'completed' then
    return true;
  end if;
  if v_status <> 'assigned'
     or jsonb_typeof(p_initial_responses) <> 'array'
     or jsonb_array_length(p_initial_responses) <> 4
     or jsonb_typeof(p_responses) <> 'array'
     or jsonb_array_length(p_responses) <> 80 then
    raise exception 'Incomplete or inactive study session';
  end if;

  insert into public.initial_ratings (
    study_session_id,
    stimulus,
    trial_number,
    glossiness,
    metallicness,
    response_time_ms
  )
  select
    p_study_session_id,
    response.stimulus,
    response.trial_number,
    response.glossiness,
    response.metallicness,
    response.response_time_ms
  from jsonb_to_recordset(p_initial_responses) as response(
    stimulus text,
    trial_number smallint,
    glossiness smallint,
    metallicness smallint,
    response_time_ms integer
  )
  on conflict (study_session_id, trial_number) do nothing;

  get diagnostics v_initial_inserted = row_count;
  if v_initial_inserted <> 4 then
    raise exception 'Initial responses are incomplete';
  end if;

  insert into public.ratings (
    study_session_id,
    stimulus_id,
    glossiness,
    metallicness,
    response_time_ms
  )
  select
    p_study_session_id,
    response.stimulus_id,
    response.glossiness,
    response.metallicness,
    response.response_time_ms
  from jsonb_to_recordset(p_responses) as response(
    stimulus_id bigint,
    glossiness smallint,
    metallicness smallint,
    response_time_ms integer
  )
  join public.session_assignments as a
    on a.study_session_id = p_study_session_id
   and a.stimulus_id = response.stimulus_id
  on conflict (study_session_id, stimulus_id) do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted <> 80 then
    raise exception 'Responses do not match the assigned stimuli';
  end if;

  update public.stimuli as s
  set
    reserved_labels = greatest(0, s.reserved_labels - 1),
    completed_labels = s.completed_labels + 1
  where s.id in (
    select a.stimulus_id
    from public.session_assignments as a
    where a.study_session_id = p_study_session_id
  );

  update public.session_assignments
  set completed = true
  where study_session_id = p_study_session_id;

  update public.study_sessions
  set status = 'completed', completed_at = now()
  where id = p_study_session_id;

  return true;
end;
$$;

revoke execute on function public.claim_study_assignment(text, text, text, text) from public;
revoke execute on function public.submit_study_session(uuid, text, jsonb, jsonb) from public;
revoke execute on function public.submit_study_session(uuid, text, jsonb) from public;
grant execute on function public.claim_study_assignment(text, text, text, text) to anon;
grant execute on function public.submit_study_session(uuid, text, jsonb, jsonb) to anon;
